# Generated by Django 4.2.13 on 2024-06-26 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Наименование одежды')),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='Загрузите фото одежды')),
                ('about_book', models.TextField(null=True, verbose_name='Об одежде')),
                ('cloth_type', models.CharField(choices=[('Clothes', 'Clothes'), ('Shoes', 'Shoes'), ('Pants', 'Pants')], max_length=20, null=True, verbose_name='Какой жанр')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('points', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_books', to='general_menu.topproduct')),
            ],
        ),
    ]
